// ----------------------------------------------------------------------

export const location = [
  'Edificio de Aulas Norte',
  'Biblioteca Central',
  'Laboratorios de Ciencias',
  'Complejo Deportivo Javeriano',
  'Cafetería El Claustro',
  'Auditorio Principal',
  'Plaza de Estudiantes',
  'Sala de Conferencias Pedro Arrupe',
  'Pabellón de Ingeniería',
  'Área de Ciencias Sociales',
  'Patio de Arte',
  'Edificio de Administración',
  'Jardines del Campus',
  'Centro de Idiomas',
  'Teatro Xavier',
  'Espacio de Investigación Ignacio Ellacuría',
  'Anfiteatro San Francisco de Borja',
  'Galería de Arte Loyola',
  'Centro de Tecnología Educativa',
  'Patio de Filosofía',
  'Espacio de Innovación Ignacio de Loyola',
  'Sala de Música San Alberto Magno',
  'Plaza de Humanidades',
  'Laboratorios de Computación',
  'Sala de Biología Ignacio Alberione',
  'Auditorio de Ciencias Sociales',
  'Pabellón de Psicología',
  'Espacio de Medicina San Ignacio',
  'Centro de Estudios Teológicos',
  'Pabellón de Comunicación',
  'Plaza de Relaciones Internacionales',
  'Patio de Derecho',
  'Edificio de Arquitectura',
  'Sala de Historia Jesuita',
  'Auditorio de Ciencias Económicas',
  'Pabellón de Educación',
  'Galería de Ciencias Naturales',
  'Espacio de Teología Juan de Lugo',
  'Laboratorios de Química y Física',
  'Biblioteca de Ciencias Sociales',
  'Centro de Investigación Médica San Lucas',
  'Área de Matemáticas y Estadísticas'  
  ];
  