// ----------------------------------------------------------------------

export const fullName = [
  'Sofía García',
  'Mateo Rodríguez',
  'Valentina Martínez',
  'Santiago Hernández',
  'Isabella López',
  'Leonardo González',
  'Juan David Aldana',
  'Sebastián Fernández',
  'Carlos Loreto',
  'Diego Ramírez',
  'Nicolás Flores',
  'Lucía Torres',
  'Miguel Rivera',
  'Fernanda Gómez',
  'Alejandro Díaz',
  'Valeria Reyes',
  'Daniel Morales',
  'Renata Cruz',
  'Mariana Rojas',
  'Ana Vargas',
  'Joaquín Castillo',
  'Adriana Núñez',
  'Camila Mendoza',
  'Paula Cortez',
  'Alejandro García',
];

export const firstName = [
  'Sofía',
  'Mateo',
  'Valentina',
  'Santiago',
  'Isabella',
  'Leonardo',
  'Juan David',
  'Sebastián',
  'Carlos',
  'Diego',
  'Nicolás',
  'Lucía',
  'Miguel',
  'Fernanda',
  'Alejandro',
  'Valeria',
  'Daniel',
  'Renata',
  'Mariana',
  'Ana',
  'Joaquín',
  'Adriana',
  'Camila',
  'Paula',
  'Alejandro',
];

export const lastName = [
  'García',
  'Rodríguez',
  'Martínez',
  'Hernández',
  'López',
  'González',
  'Aldana',
  'Fernández',
  'Loreto',
  'Ramírez',
  'Flores',
  'Torres',
  'Rivera',
  'Gómez',
  'Díaz',
  'Reyes',
  'Morales',
  'Cruz',
  'Rojas',
  'Vargas',
  'Castillo',
  'Núñez',
  'Mendoza',
  'Cortez',
];
